---
title: "Summarize data"
format:
  html:
    code-fold: true
    embed-resources: true
editor: source
---

## Libraries etc

```{r}
library(here)

library(data.table)
library(DT)

library(ggplot2)
library(rnaturalearth)
library(dplyr)

library(sf)

read_folder <- here("data/03_grid")
fig_folder <- here("figures/03_data_summary")
```

## Prepare data

### Read data

```{r}
df_steli <- readRDS(file.path(read_folder, "steli.rds"))
df_atlas <- readRDS(file.path(read_folder, "atlas.rds"))

df_steli <- as.data.table(df_steli)
df_atlas <- as.data.table(df_atlas)
```

### Format data

```{r}
df_steli[, source := "STELI"]
df_atlas[, source := "atlas"]
```

```{r}
dat <- rbind(df_steli,
             df_atlas,
             fill = TRUE)
```

```{r}
rm(df_atlas)
rm(df_steli)
```

```{r}
# Filter only species level information
dat <- dat[taxonRank == "SPECIES", ]
```

## Summarize data

### Tables

```{r}
# Number of observations by program
dat[, .N, by = source] |> 
  datatable()

# Number of species
nsp <- dat[, .N, by = scientificName][order(-N), ]

nsp |> datatable()
```

## Species barplot

```{r, fig.height=6, fig.width=8}
ggplot(nsp) +
  geom_col(aes(x = N, 
               y = reorder(scientificName, N)), fill = "darkorange") +
  scale_x_continuous(expand = c(0,0)) +
  xlab("Number of occurrences") +
  theme_minimal(base_size = 16) +
  theme(axis.title.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_text(face = "italic",
                                   size = 6))

ggsave(file.path(fig_folder, "spp_barplot.png"),
       width = 8, height = 6, dpi = 300)
```

### Data evolution

```{r, fig.width=6, fig.height=3}
datN <- dat[, .N, by = list(source, year(dat$eventDate))]

ggplot(datN) +
  geom_line(aes(x = year, y = N)) +
  # geom_point(aes(x = year, y = N)) +
  theme_minimal() +
  ylab("Occurrences") +
  scale_y_continuous(labels = function(x) format(x, big.mark = ",")) +
  # scale_x_continuous(breaks = c(seq(1700, 1900, by = 100),
  #                               seq(1990, 2024, by = 10))) +
  # # scale_x_continuous(breaks = seq(2010, 2025, by = 5)) +
  facet_wrap(facets = vars(source), 
             scales = "free") +
  theme(axis.title.x = element_blank())

ggsave(file.path(fig_folder, "dat_evolution.png"),
       width = 6, height = 3, dpi = 300)
```

### Map

```{r}
dat_sf <- st_as_sf(dat,
                   wkt = "decimalCoordinates")
st_crs(dat_sf) <- 4326

# Transform
dat_3035 <- st_transform(dat_sf, crs = 3035)
```

```{r}
# Get French map
fr <- ne_countries(scale = 50, 
                   country = "France")
fr_3035 <- st_transform(fr, 3035)

# Data bounding box
bbox <- st_bbox(dat_3035)
```

Plot raw data points:

```{r}
ggplot() +
  geom_sf(data = fr_3035) +
  xlim(bbox$xmin, bbox$xmax) +
  ylim(bbox$ymin, bbox$ymax) +
  geom_sf(data = dat_3035,
          aes(col = source), size = 0.1) +
  facet_wrap(facets = vars(source))
```

Plot data on grid:

```{r}
# Get grid
grid <- readRDS(file.path(read_folder, 
                          "grid_scale_10000.rds"))
```

```{r}
# Sumarize with grid
nobs <- st_drop_geometry(dat) |>
  group_by(id_10000) |>
  summarize(nobs = n(), .groups = "drop")

nobs_grid <- grid |>
  right_join(nobs, by = c("id" = "id_10000"))
nobs_grid <- st_intersection(nobs_grid, fr_3035)
```

```{r}
# Plot data
ggplot() +
  geom_sf(data = fr_3035) +
  geom_sf(data = nobs_grid, aes(fill = nobs),
          color = "transparent") +
  # facet_grid(cols = vars(source)) +
  xlim(bbox$xmin, bbox$xmax) +
  ylim(bbox$ymin, bbox$ymax) +
  scale_fill_viridis_c(na.value = "lightgrey",
                       trans = "log",
                       breaks = c(1, 20, 400, 8000),
                       name = "Occurrences") +
  theme_void(base_size = 30) + 
  theme(legend.position = "left",
        legend.key.height = unit(1, "cm"))

ggsave(file.path(fig_folder, "map.png"),
       width = 8, height = 6, dpi = 300)
```

